name: Add Release Label

on:
  pull_request:
    types:
      - opened
      - ready_for_review
#    branches:
#      - release
    

jobs:
  release-label:
    name: Add Release Label
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get Issue Number from Branch Name
      id: issue_number
      run: |
        echo "${{ github.event.pull_request.head.ref }}" | awk '{ gsub(/[^0-9].*/, "", $0); print "number="$0; }' >> $GITHUB_OUTPUT
    - uses: actions/github-script@v6
      id: my-script
      env:
          ISSUE_NUMBER: '${{ steps.issue_number.outputs.number }}'
      with:
        script: |
          const { ISSUE_NUMBER } = process.env
          console.log(`Issue Number: ${ISSUE_NUMBER}`)
          if (ISSUE_NUMBER.length < 2) {
            console.log('Issue NUmber to short.')
            return
          }
          const issue = await github.rest.issues.get({
            issue_number: ISSUE_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          console.log(issue)

