name: Add Release Label

on:
  pull_request:
    types:
      - opened
      - ready_for_review
#    branches:
#      - release
    

jobs:
  release-label:
    name: Add Release Label
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Get Issue Number from Branch Name
      id: issue_number
      run: |
        echo "${{ github.event.ref }}" | awk '{ gsub(/[^0-9].*/, "", $0); print "number="$0; }' >> $GITHUB_OUTPUT
    - uses: actions/github-script@v6
      id: my-script
      env:
          ISSUE_NUMBER: '35'
      with:
        script: |
          cont number = process.env.ISSUE_NUMBER
          console.log(ISSUE_NUMBER);
          const issue = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: number,
          });
          console.log(issue);
          const labels = issue.data.labels.map(label => label.name);
          console.log(labels);
