name: Move Card on Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  move-card:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Find issue number associated with PR
        id: get-issue
        run: |
          issue_number=$(gh pr view ${PR_NUMBER} --json linkedIssues --jq '.linkedIssues[0].number')
          echo "::set-output name=issue_number::$issue_number"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
      - name: Find card ID associated with the issue
        id: get-card
        run: |
          card_id=$(gh api projects/columns/cards -X GET -F column_id=${COLUMN_ID} --jq '.[] | select(.content_url | contains("issues/${ISSUE_NUMBER}")) | .id')
          echo "::set-output name=card_id::$card_id"
        env:
          COLUMN_ID: <source_column_id> # ID of the column where the card currently is
          ISSUE_NUMBER: ${{ steps.get-issue.outputs.issue_number }}
          
      - name: Move card to "Changes Requested" column
        run: |
          gh api projects/columns/cards/${CARD_ID}/moves -X POST -F position=bottom -F column_id=${COLUMN_ID}
        env:
          CARD_ID: ${{ steps.get-card.outputs.card_id }}
          COLUMN_ID: <destination_column_id> # ID of your "Changes Requested" column
