name: Create and/or Update edited issues to my project

on:
  issues:
    types:
      - opened

jobs:
  create-update-project:
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
        with:
          project-url: https://github.com/users/janiswehen/projects/1
          github-token: ${{ secrets.GHPROJECT_SECRET }}
        id: add-project
      - uses: EndBug/project-fields@v1
        with:
          fields: Review Status
          github_token: ${{ secrets.GHPROJECT_SECRET }}
          project_url: https://github.com/users/janiswehen/projects/1
          resource_url: https://github.com/janiswehen/AI-Functions/issues/${{ github.event.issue.number }}
          values: Approved
#      - uses: titoportas/update-project-fields@v0.1.0
#        with:
#          project-url: https://github.com/users/titoportas/projects/2
#          github-token: ${{ secrets.GHPROJECT_SECRET }}
#          item-id: ${{ steps.add-project.outputs.itemId }} # Use the item-id output of the previous step
#          field-keys: Review Status
#          field-values: Approved
