name: Update Project Status to Backlog

on:
  project_card:
    types:
      - created

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Update Project Status to Backlog
        run: echo 'test'
