name: Update Project Fields for PR

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft, closed]
    branches:
      - main

jobs:
  project-draft-pr:
    if: ${{ github.event.pull_request.draft == true }} && ${{ github.event.pull_request.merged == false }}
    name: Update Project Item Draft PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
#        with:
#          project-url: https://github.com/users/janiswehen/projects/1
#          github-token: ${{ secrets.GHPROJECT_SECRET }}
#        id: add-project
      - uses: EndBug/project-fields@v1 # Changes the project field
        with:
          fields: Review Status
          github_token: ${{ secrets.GHPROJECT_SECRET }}
          project_url: https://github.com/users/janiswehen/projects/1
          resource_url: https://github.com/janiswehen/AI-Functions/pull/${{ github.event.pull_request.number }}
          values: Develop
  project-pr-ready:
    if: ${{ github.event.pull_request.draft == false }} && ${{ github.event.pull_request.merged == false }}
    name: Update Project Item for PR ready for review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
#        with:
#          project-url: https://github.com/users/janiswehen/projects/1
#          github-token: ${{ secrets.GHPROJECT_SECRET }}
#        id: add-project
      - uses: EndBug/project-fields@v1 # Changes the project field
        with:
          fields: Review Status
          github_token: ${{ secrets.GHPROJECT_SECRET }}
          project_url: https://github.com/users/janiswehen/projects/1
          resource_url: https://github.com/janiswehen/AI-Functions/pull/${{ github.event.pull_request.number }}
          values: Ready to Review
  project-pr-merged:
    if: ${{ github.event.pull_request.merged == true }}
    name: Update Project Item for PR merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/project-fields@v1 # Changes the project field
        with:
          fields: Review Status
          github_token: ${{ secrets.GHPROJECT_SECRET }}
          project_url: https://github.com/users/janiswehen/projects/1
          resource_url: https://github.com/janiswehen/AI-Functions/pull/${{ github.event.pull_request.number }}
          values: ✨ Merged
