name: Add Labels

on:
  pull_request:
    types:
      - opened

jobs:
  transfer-labels:
    name: Transfer labels from Issue to PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install jq
      run: sudo apt-get install jq

    - name: Give execution permission to script
      run: chmod +x .github/workflows/scripts/*.sh

    - name: Run script to transfer labels
      run: ./.github/workflows/scripts/transfer_labels.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GHPROJECT_SECRET }}
        BRANCH_NAME: ${{ github.head_ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
  release-label:
    name: Add Release Label
    if: ${{ github.event.pull_request.base.ref == 'release' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install jq
      run: sudo apt-get install jq

    - name: Give execution permission to script
      run: chmod +x .github/workflows/scripts/*.sh

    - name: Run script to transfer labels
      run: ./.github/workflows/scripts/release_label.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GHPROJECT_SECRET }}
        BRANCH_NAME: ${{ github.head_ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}