name: Add Labels

on:
  pull_request:
    types:
      - opened

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup scripts
        uses: ./.github/workflows/scripts/setup_scripts.yml