name: Find Issue

on:
  pull_request:
    types:
      - opened

jobs:
  find-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install jq
      run: sudo apt-get install jq

    - name: Give execution permission to script
      run: chmod +x .github/workflows/scripts/find_issue.sh

    - name: Run script to find issue
      run: ./.github/workflows/scripts/find_issue.sh "${{ github.head_ref }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GHPROJECT_SECRET }}
