name: Add in progress label to issue

on:
  pull_request:
    types: [opened]

jobs:
  add_in_progress:
    if: ${{ github.head_ref =~ ^\d{4,5} }}
    name: Update Project Item Draft PR
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch name
        run: echo "ISSUE_NUMBER=$(echo ${{ github.head_ref }} | grep -oP '^\d{4,5}')" >> $GITHUB_ENV

      - name: Add 'in_Progress' label to the issue
        run: |
          curl -s \
               -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}/labels \
               -d '{"labels": ["in_Progress"]}'
